### PR TITLE
Add three vignettes for running BioCro and ED2 models

### PR DESCRIPTION
**Pull request by KristinaRiemer**

### CODE REVIEW

**Comment by dlebauer** [comment]
maybe make another repository dedicated to running models?

**Comment by dlebauer** [comment]
And, did you mean to check in all of these images and h5 files?

**Comment by KristinaRiemer** [comment]
The h5 files are needed to knit the ED2 vignette. What images?

**Comment by KristinaRiemer** [comment]
I can create a new repo for these if you want.

**Comment by dlebauer** [comment]
yep, a new repo would be good. Lets think about the intent ... 

* vignettes documenting specific analyses for the APT project can go there
* vignettes intended to demonstrate how to use the models can go in a repository of tutorials (or maybe one specific for model tutorials) 

With respect to files, I know we've discussed this before but 

* images like the biocro output. https://github.com/az-digitalag/organization/blob/d3feb52ccbbf2792cfdae14be7ce038cdca8833b/model_vignettes/biocro_lai_plot.png can be generated by knitting or, in the case of tutorials, if coupled to TravisCI
* the h5 files will quickly bloat the repository ... what are other options? 
   * can these be downloaded from a production (rather than VM) website like welsch on demand?
   * put on Box, google drive, Cyverse data store or ???
   * generated as part of an end-to-end workflow?

**Comment by KristinaRiemer** [comment]
APT project vignettes go in the sentinel detection repo? Definitely agree with having those be distinct from the more general how-to-use-the-models vignettes. 

I would very much like for all those files/plots to be generated along the way, this was just the short-term hacky solution to track what I've done so far, but we should definitely talk about what that will look like.

**Comment by KristinaRiemer** [comment]
Closing this as the vignettes are being migrated to a new repo in this organization.

**Comment by KristinaRiemer** [comment]
See PR [here](https://github.com/az-digitalag/model-vignettes/pull/1).

**Pull request closed without merging**
